nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

# The rust dependency causes issues
# fix with this
# https://stackoverflow.com/questions/49501749/is-it-possible-to-ignore-the-dependency-hash-validation-of-just-one-module-or-r
--install.update-checksums true